### ISSUE TITLE
ShellTask::run not working

### ISSUE THREAD

**Issue by danfsd** [idfly/yii2-shell-task#1]
Hello, first of all I would like to say that among all the Console/Command task runners, yours is the most promising, and I'm very excited to use it.

I'm trying to setup the module and run a simple task:
Create a folder on my OS User folder

``` php
class MatchController extends \yii\console\Controller
{
    public function actionCreate() {
        mkdir("/Users/danfsd/test");
        echo "Hello World";
        return 0;
    }
}
```

And this is my ShellTask code:

``` php
class SiteController extends \yii\web\Controller
{
     public function actionIndex() {
           $options = [
                 'concurrent' => true
           ];
           ShellTask::run("match/create", $options);
     }
}
```

And of course, I didn't forget about the module on the configuration file

``` php
$config['modules']['shellTask'] = ['class' => 'idfly\shellTask\Module'];
```

What happens is that It's simply not working, I'm looking into my folder and it is not created.
Am I doing something wrong here? Is there a way to debug the execution?

Thanks in advance

**Comment by shagabutdinov** [comment]
Please specify your OS and php version and show latest records/files in runtime/tasks and runtime/logs.

**Comment by danfsd** [comment]
I tried both on Windows 10 and Mac OS El Capitan operational systems.
On Mac I used MAMP with the PHP 5.6
On Windows I used Xampp with PHP 5.6 as well.

Inside runtime/tasks there was a folder called match--create.async, but with no files inside.

Inside runtime/logs there was a file called app.logs, but with no recent logs (refering the test day)

**Comment by shagabutdinov** [comment]
Sorry, this module is not intended to work under windows, because it use linux-specific utilities to lock tasks. Also we didn't test it under MacOS and we do not have possibility to test it under this OS, because whole team are working under linux'es. I suggest you to use vagrant/docker with any linux distribution to run this module.
